name: Sync Repositories

on:
  push:
    branches:
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure Git
        run: |
          git config --global user.email "ariel.chambaz@epitech.eu"
          git config --global user.name "ArielChambaz"
          git config --global pull.rebase false  # Use merge strategy by default

      - name: Pull from destination repository
        env:
          DEST_REPO: git@github.com:EpitechPromo2026/G-EIP-700-REN-7-1-eip-adrien.picot.git
        run: |
          git remote add dest $DEST_REPO
          git fetch dest
          git checkout ${{ github.ref_name }}
          git pull dest ${{ github.ref_name }} --allow-unrelated-histories

      - name: Remove .github directory
        run: |
          rm -rf .github

      - name: Clean and repack repository
        run: |
          git gc --aggressive --prune=now
          git repack -a -d --depth=250 --window=250

      - name: Get last commit message
        id: get_commit_message
        run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Sync current branch
        env:
          DEST_REPO: git@github.com:EpitechPromo2026/G-EIP-700-REN-7-1-eip-adrien.picot.git
        run: |
          git add -A
          git commit -m "${{ env.COMMIT_MESSAGE }}"
          git push $DEST_REPO ${{ github.ref_name }} --force